wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.14.2
    framework: huggingface
    huggingface_version: 4.28.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1682301080.335958
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      3:
      - 13
      - 23
      4: 3.9.16
      5: 0.14.2
      6: 4.28.0
      8:
      - 1
      - 5
